name: flags_binary
description: a package for handling bits (0, 1) binary state
version: 0.0.2
repository: https://github.com/nomagicisreal/flags_binary

environment:
  sdk: ^3.8.1

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
